export const document = {
  ROOT: {
    type: { resolvedName: "Canvas" },
    isCanvas: true,
    props: { className: "w-full h-full", id: "ROOT" },
    displayName: "div",
    custom: {},
    hidden: false,
    nodes: ["pW58oM1qw_"],
    linkedNodes: {},
  },
  tjH29Qsghs: {
    type: { resolvedName: "NodeButton" },
    isCanvas: false,
    props: { children: "Button 1" },
    displayName: "Button",
    custom: { importPath: "@/components/button" },
    parent: "ROOT",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  MTxhyV78i9: {
    type: { resolvedName: "NodeButton" },
    isCanvas: false,
    props: { children: "Button 2" },
    displayName: "Button",
    custom: { importPath: "@/components/button" },
    parent: "ROOT",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  MInyBoxsBP: {
    type: { resolvedName: "NodeButton" },
    isCanvas: false,
    props: { children: "Button 3" },
    displayName: "Button",
    custom: { importPath: "@/components/button" },
    parent: "ROOT",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  GvqHsxzUxy: {
    type: { resolvedName: "NodeButton" },
    isCanvas: false,
    props: { children: "Button 4" },
    displayName: "Button",
    custom: { importPath: "@/components/button" },
    parent: "ROOT",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  pW58oM1qw_: {
    type: { resolvedName: "NodeTwoBlocks" },
    isCanvas: false,
    props: { className: "flex flex-row m-2 p-4" },
    displayName: "div",
    custom: {},
    parent: "ROOT",
    hidden: false,
    nodes: [],
    linkedNodes: { "first-block": "cohzgqfAl_", "second-block": "uwGvWmFTvG" },
  },
  cohzgqfAl_: {
    type: { resolvedName: "NodeOneBlock" },
    isCanvas: true,
    props: { className: "w-full" },
    displayName: "div",
    custom: { importPath: "" },
    parent: "pW58oM1qw_",
    hidden: false,
    nodes: ["LZWD4hgosK"],
    linkedNodes: {},
  },
  uwGvWmFTvG: {
    type: { resolvedName: "NodeOneBlock" },
    isCanvas: true,
    props: { className: "w-full" },
    displayName: "div",
    custom: { importPath: "" },
    parent: "pW58oM1qw_",
    hidden: false,
    nodes: ["3J0gemMluq"],
    linkedNodes: {},
  },
  LZWD4hgosK: {
    type: { resolvedName: "NodeCard" },
    isCanvas: false,
    props: { className: "p-6 m-2" },
    displayName: "Card",
    custom: { importPath: "@/components/card" },
    parent: "cohzgqfAl_",
    hidden: false,
    nodes: [],
    linkedNodes: { "card-header": "5Jd8LxFtZk", "card-content": "zEPdEhW0av", "card-footer": "os2eZsBJyQ" },
  },
  "5Jd8LxFtZk": {
    type: { resolvedName: "NodeCardHeader" },
    isCanvas: true,
    props: {},
    displayName: "CardHeader",
    custom: { importPath: "@/components/card" },
    parent: "LZWD4hgosK",
    hidden: false,
    nodes: ["R3svVpL8sb", "dZLd5fJiM3"],
    linkedNodes: {},
  },
  R3svVpL8sb: {
    type: { resolvedName: "NodeCardTitle" },
    isCanvas: false,
    props: { children: "Card Title" },
    displayName: "CardTitle",
    custom: { importPath: "@/components/card" },
    parent: "5Jd8LxFtZk",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  dZLd5fJiM3: {
    type: { resolvedName: "NodeCardDescription" },
    isCanvas: false,
    props: { children: "Card Description" },
    displayName: "CardDescription",
    custom: { importPath: "@/components/card" },
    parent: "5Jd8LxFtZk",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  zEPdEhW0av: {
    type: { resolvedName: "NodeCardContent" },
    isCanvas: true,
    props: {},
    displayName: "CardContent",
    custom: { importPath: "@/components/card" },
    parent: "LZWD4hgosK",
    hidden: false,
    nodes: ["x8f-cgPToC", "E-q-ZJ1dyY"],
    linkedNodes: {},
  },
  os2eZsBJyQ: {
    type: { resolvedName: "NodeCardFooter" },
    isCanvas: true,
    props: {},
    displayName: "CardFooter",
    custom: { importPath: "@/components/card" },
    parent: "LZWD4hgosK",
    hidden: false,
    nodes: ["wPGGk5Bu9H"],
    linkedNodes: {},
  },
  wPGGk5Bu9H: {
    type: { resolvedName: "NodeButton" },
    isCanvas: false,
    props: { children: "Footer button" },
    displayName: "Button",
    custom: { importPath: "@/components/button" },
    parent: "os2eZsBJyQ",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "3J0gemMluq": {
    type: { resolvedName: "NodeCard" },
    isCanvas: false,
    props: { className: "p-6 m-2" },
    displayName: "Card",
    custom: { importPath: "@/components/card" },
    parent: "uwGvWmFTvG",
    hidden: false,
    nodes: [],
    linkedNodes: { "card-header": "gr7LgpqtF3", "card-content": "BevZ1OVESc", "card-footer": "NWrXLscpxK" },
  },
  gr7LgpqtF3: {
    type: { resolvedName: "NodeCardHeader" },
    isCanvas: true,
    props: {},
    displayName: "CardHeader",
    custom: { importPath: "@/components/card" },
    parent: "3J0gemMluq",
    hidden: false,
    nodes: ["vMJk07snsU", "vzIa1Nyd3-"],
    linkedNodes: {},
  },
  vMJk07snsU: {
    type: { resolvedName: "NodeCardTitle" },
    isCanvas: false,
    props: { children: "Card Title" },
    displayName: "CardTitle",
    custom: { importPath: "@/components/card" },
    parent: "gr7LgpqtF3",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "vzIa1Nyd3-": {
    type: { resolvedName: "NodeCardDescription" },
    isCanvas: false,
    props: { children: "Card Description" },
    displayName: "CardDescription",
    custom: { importPath: "@/components/card" },
    parent: "gr7LgpqtF3",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  BevZ1OVESc: {
    type: { resolvedName: "NodeCardContent" },
    isCanvas: true,
    props: {},
    displayName: "CardContent",
    custom: { importPath: "@/components/card" },
    parent: "3J0gemMluq",
    hidden: false,
    nodes: ["2cdp_J0uXF", "V1QLiq1fqp"],
    linkedNodes: {},
  },
  NWrXLscpxK: {
    type: { resolvedName: "NodeCardFooter" },
    isCanvas: true,
    props: {},
    displayName: "CardFooter",
    custom: { importPath: "@/components/card" },
    parent: "3J0gemMluq",
    hidden: false,
    nodes: ["zGktPJfR5Y"],
    linkedNodes: {},
  },
  zGktPJfR5Y: {
    type: { resolvedName: "NodeButton" },
    isCanvas: false,
    props: { children: "Footer button" },
    displayName: "Button",
    custom: { importPath: "@/components/button" },
    parent: "NWrXLscpxK",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "x8f-cgPToC": {
    type: { resolvedName: "NodeButton" },
    isCanvas: false,
    props: { variant: "destructive", children: "Destructive" },
    displayName: "Button",
    custom: { importPath: "@/components/button" },
    parent: "zEPdEhW0av",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "E-q-ZJ1dyY": {
    type: { resolvedName: "NodeButton" },
    isCanvas: false,
    props: { children: "Default" },
    displayName: "Button",
    custom: { importPath: "@/components/button" },
    parent: "zEPdEhW0av",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "2cdp_J0uXF": {
    type: { resolvedName: "NodeButton" },
    isCanvas: false,
    props: { children: "Default" },
    displayName: "Button",
    custom: { importPath: "@/components/button" },
    parent: "BevZ1OVESc",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  V1QLiq1fqp: {
    type: { resolvedName: "NodeButton" },
    isCanvas: false,
    props: { variant: "destructive", children: "Destructive" },
    displayName: "Button",
    custom: { importPath: "@/components/button" },
    parent: "BevZ1OVESc",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};
